#!/bin/bash
# =============================================================================
# Coturn TURN Server Setup Script for Exclusive Messenger
# Run this on your VPS (same server as the app)
# =============================================================================
#
# Prerequisites:
#   1. A subdomain (e.g. turn.yourdomain.com) pointing to this server's IP
#   2. Ports 3478, 5349 (TCP/UDP) and 49152-65535 (UDP) open in firewall
#
# Usage:
#   chmod +x scripts/setup-coturn.sh
#   sudo bash scripts/setup-coturn.sh --domain turn.yourdomain.com --secret YOUR_SECRET
#
# =============================================================================

set -euo pipefail

# Parse arguments
TURN_DOMAIN=""
TURN_SECRET=""
SERVER_IP=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain) TURN_DOMAIN="$2"; shift 2 ;;
    --secret) TURN_SECRET="$2"; shift 2 ;;
    --ip) SERVER_IP="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [ -z "$TURN_DOMAIN" ]; then
  echo "Error: --domain is required (e.g. --domain turn.yourdomain.com)"
  exit 1
fi

# Generate secret if not provided
if [ -z "$TURN_SECRET" ]; then
  TURN_SECRET=$(openssl rand -hex 32)
  echo "Generated TURN_SECRET: $TURN_SECRET"
fi

# Auto-detect server IP if not provided
if [ -z "$SERVER_IP" ]; then
  SERVER_IP=$(curl -s https://api.ipify.org || hostname -I | awk '{print $1}')
  echo "Detected server IP: $SERVER_IP"
fi

echo "=== Installing Coturn ==="
apt-get update -qq
apt-get install -y coturn

echo "=== Enabling Coturn service ==="
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

echo "=== Obtaining SSL certificate for $TURN_DOMAIN ==="
# Use certbot standalone (stop nginx temporarily if needed)
if command -v certbot &> /dev/null; then
  # Check if cert already exists
  if [ ! -d "/etc/letsencrypt/live/$TURN_DOMAIN" ]; then
    certbot certonly --standalone --non-interactive --agree-tos \
      --email admin@${TURN_DOMAIN#*.} \
      -d "$TURN_DOMAIN" \
      --preferred-challenges http \
      --pre-hook "docker stop em-web-prod 2>/dev/null || true" \
      --post-hook "docker start em-web-prod 2>/dev/null || true"
  else
    echo "SSL certificate already exists for $TURN_DOMAIN"
  fi
else
  apt-get install -y certbot
  certbot certonly --standalone --non-interactive --agree-tos \
    --email admin@${TURN_DOMAIN#*.} \
    -d "$TURN_DOMAIN" \
    --preferred-challenges http \
    --pre-hook "docker stop em-web-prod 2>/dev/null || true" \
    --post-hook "docker start em-web-prod 2>/dev/null || true"
fi

echo "=== Configuring Coturn ==="
cat > /etc/turnserver.conf << TURNEOF
# Coturn configuration for Exclusive Messenger
# Generated by setup-coturn.sh

# Network
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
external-ip=$SERVER_IP
relay-ip=$SERVER_IP

# Domain
realm=$TURN_DOMAIN
server-name=$TURN_DOMAIN

# Authentication (use long-term credentials with shared secret)
use-auth-secret
static-auth-secret=$TURN_SECRET

# TLS
cert=/etc/letsencrypt/live/$TURN_DOMAIN/fullchain.pem
pkey=/etc/letsencrypt/live/$TURN_DOMAIN/privkey.pem

# Security
no-multicast-peers
no-cli
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255

# Relay port range
min-port=49152
max-port=65535

# Logging
log-file=/var/log/coturn/turnserver.log
simple-log
new-log-timestamp

# Performance
total-quota=100
stale-nonce=600
max-bps=0

# Fingerprint for STUN messages
fingerprint
TURNEOF

# Create log directory
mkdir -p /var/log/coturn
chown turnserver:turnserver /var/log/coturn 2>/dev/null || true

# Allow coturn to read SSL certs
chmod 755 /etc/letsencrypt/live/ 2>/dev/null || true
chmod 755 /etc/letsencrypt/archive/ 2>/dev/null || true

echo "=== Opening firewall ports ==="
if command -v ufw &> /dev/null; then
  ufw allow 3478/tcp
  ufw allow 3478/udp
  ufw allow 5349/tcp
  ufw allow 5349/udp
  ufw allow 49152:65535/udp
  echo "UFW rules added"
fi

echo "=== Starting Coturn ==="
systemctl enable coturn
systemctl restart coturn
sleep 2

if systemctl is-active --quiet coturn; then
  echo "=== Coturn is running! ==="
else
  echo "=== WARNING: Coturn failed to start. Check: journalctl -u coturn ==="
fi

echo ""
echo "============================================="
echo "  Coturn Setup Complete!"
echo "============================================="
echo ""
echo "  TURN Domain:  $TURN_DOMAIN"
echo "  TURN Secret:  $TURN_SECRET"
echo "  Server IP:    $SERVER_IP"
echo ""
echo "  Next steps:"
echo "  1. Add a DNS A record: $TURN_DOMAIN -> $SERVER_IP"
echo "  2. Add these to your .env on the VPS:"
echo ""
echo "     TURN_SERVER=$TURN_DOMAIN"
echo "     TURN_SECRET=$TURN_SECRET"
echo ""
echo "  3. Rebuild and restart the backend:"
echo "     cd /root/exmsg/docker"
echo "     docker compose -f docker-compose.prod.yml build --no-cache backend"
echo "     docker compose -f docker-compose.prod.yml up -d backend"
echo ""
echo "  Test with: turnutils_uclient -t -u test -w test $TURN_DOMAIN"
echo "============================================="
